# Generated by Django 3.2.6 on 2021-08-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
