# Generated by Django 3.2.6 on 2021-08-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='Seller',
        ),
    ]
