# Generated by Django 3.2.6 on 2021-08-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itens', '0002_alter_item_price'),
        ('clients', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
    ]
