# Generated by Django 3.2.6 on 2021-08-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_alter_item_price'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='itens',
        ),
        migrations.AddField(
            model_name='cart',
            name='itens',
            field=models.ManyToManyField(to='itens.Item'),
        ),
    ]
