# Generated by Django 3.2.6 on 2021-08-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_alter_item_price'),
        ('carts', '0003_auto_20210816_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itens',
            field=models.ManyToManyField(blank=True, null=True, to='itens.Item'),
        ),
    ]
