# Generated by Django 3.2.6 on 2021-08-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20210818_1359'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
